"use client";
import { Area, Bar, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { cumulativeR, drawdownSeries, type EquityPoint, type TradePoint } from "@/lib/analytics/chart-data";

export function PerformanceCharts({ equity, trades }: { equity: EquityPoint[]; trades: TradePoint[] }) {
  const drawdown = drawdownSeries(equity);
  const r = cumulativeR(trades);
  return <div className="grid gap-4 xl:grid-cols-2"><Chart title="Equity over time"><ResponsiveContainer width="100%" height={260}><ComposedChart data={equity}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.15)" /><XAxis dataKey="time" tickFormatter={(v) => new Date(v).toLocaleDateString()} /><YAxis tickFormatter={(v) => "$" + v} /><Tooltip labelFormatter={(v) => new Date(Number(v)).toLocaleString()} /><Line dataKey="equity" stroke="#60a5fa" dot={false} /></ComposedChart></ResponsiveContainer></Chart><Chart title="Drawdown"><ResponsiveContainer width="100%" height={260}><AreaChart data={drawdown} /></ResponsiveContainer></Chart><Chart title="Cumulative realized R"><ResponsiveContainer width="100%" height={260}><ComposedChart data={r}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.15)" /><XAxis dataKey="index" /><YAxis /><Tooltip /><Line dataKey="cumulativeR" stroke="#60a5fa" dot={false} /></ComposedChart></ResponsiveContainer></Chart><Chart title="R result per actual trade"><ResponsiveContainer width="100%" height={260}><ComposedChart data={r}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.15)" /><XAxis dataKey="index" /><YAxis /><Tooltip /><Bar dataKey="r" fill="#60a5fa" /></ComposedChart></ResponsiveContainer></Chart></div>;
}
function AreaChart({ data }: { data: { time: number; drawdown: number }[] }) { return <ComposedChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,.15)" /><XAxis dataKey="time" tickFormatter={(v) => new Date(v).toLocaleDateString()} /><YAxis tickFormatter={(v) => v + "%"} /><Tooltip labelFormatter={(v) => new Date(Number(v)).toLocaleString()} /><Area dataKey="drawdown" stroke="#d45b5b" fill="rgba(212,91,91,.2)" /></ComposedChart>; }
function Chart({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-lg border p-4"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{children}</div>; }
