-- Research backfill: let the job principal own its own cursors.
--
-- ADDITIVE ONLY. The existing owner_write policy is untouched; this adds a
-- second policy alongside it (permissive policies OR together).
--
-- The bounded historical backfill runs as the scanner principal, like every
-- other scheduled job, so it must be able to read and advance its resume
-- cursor in research_backfill_jobs. Without this the job cannot record where
-- it got to and would restart from the beginning on every invocation.
--
-- This grants nothing over trading state: research_backfill_jobs holds only
-- symbol, timeframe and a pagination cursor.
drop policy if exists scanner_write_research_backfill_jobs on public.research_backfill_jobs;
create policy scanner_write_research_backfill_jobs on public.research_backfill_jobs
  for all to authenticated
  using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'scanner')
  with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'scanner');

-- Research hypotheses are generated by the analysis job, which also runs as
-- the scanner principal. A hypothesis is a recorded observation awaiting
-- owner review - it can never change a strategy on its own.
drop policy if exists scanner_write_research_hypotheses on public.research_hypotheses;
create policy scanner_write_research_hypotheses on public.research_hypotheses
  for all to authenticated
  using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'scanner')
  with check (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'scanner');

comment on table public.research_backfill_jobs is
  'Resume cursors for the bounded research-only historical backfill. Deliberately separate from the live scanner watermark: the backfill only ever extends history BACKWARDS from the oldest candle already stored, so it can never mark a recent candle as already processed.';
